export const FETCH_POST_REQUEST ='FETCH_POST_REQUEST';
export const FETCH_POST_SUCCESS ='FETCH_POST_SUCCESS';
export const FETCH_POST_FAILURE ='FETCH_POST_FAILURE';
export const ADD_POST_TO_FAVIOURITE ='ADD_POST_TO_FAVIOURITE';
export const REMOVE_POST_FROM_FAVIOURITE ='REMOVE_POST_FROM_FAVIOURITE';